In [1]:
import numpy as np 
import pandas as pd 

In [32]:
data=pd.read_csv("E:/AI ML/letsupgrade/Material/Day 25/train.csv")

from sklearn import preprocessing
encoded=preprocessing.LabelEncoder()
data["Sex"]=encoded.fit_transform(data["Sex"])
data["Embarked"]=encoded.fit_transform(data["Embarked"])
x=data.drop(["Name","Ticket","Cabin","PassengerId","Pclass"],axis=1)
z=data["Pclass"]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,z,test_size=0.3,random_state=0)

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [30]:
def KNN(X_train,y_train,X_test,y_test,l):
    i=2
    t=0
    w=0
    while i<(l):
        from sklearn import neighbors
        k_model=neighbors.KNeighborsClassifier(n_neighbors=i)
        k_model.fit(X=X_train,y=y_train)
        p=k_model.score(X_test,y_test)
        
        if p>=t:
            t=p
            w=i
        i+=1
    print("Model gives maximim accuracy when there are",w,"neighbours and that value is",t)
    

In [31]:
KNN(X_train,y_train,X_test,y_test,len(X_train))

Model gives maximim accuracy when there are 3 neighbours and that value is 0.8651685393258427


## Model gives maximim accuracy when there are 1 neighbours and that value is 0.8913857677902621

# Confusion matrix of the max one:-

In [34]:
k_model1=neighbors.KNeighborsClassifier(n_neighbors=1)
k_model1.fit(X=X_train,y=y_train)
y_pred=k_model1.predict(X_test)
h=confusion_matrix(y_test,y_pred)
print(h)

[[ 62   6   2]
 [  3  37   9]
 [  1   8 139]]
