In [5]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# CLASSIFICATION TECHNIQUES:-
## 1. NAIVE BAYES THEOREM:-
### Categorical,categorical,classifiaction technique used to classify records using probability.
## 2. K- NEAREST NEIGHBOUR(KNN):-
### Categorical,categorical and Continous,classifiaction technique used to classify records with the help of euclidean distance.
## 3. SUPPORT VECTOR MACHINE(SVM):-
### Categorical,categorical and classification,classifiaction technique used to classify records with the help of hyperplane and is capable of over-dimensional data.


In [6]:
#chdir
import os
os.getcwd()

'C:\\Users\\lakshay'

In [7]:
os.chdir("C:/Users/lakshay/Desktop/MACHINE_LEARNIG_REEMERGING/TITANIC/")
os.getcwd()

'C:\\Users\\lakshay\\Desktop\\MACHINE_LEARNIG_REEMERGING\\TITANIC'

In [8]:
data=pd.read_csv("train.csv")

In [9]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
#drop name and ticket  
data=data.drop(["Name","Ticket","PassengerId"],axis=1)

In [11]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [12]:
data.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [13]:
data["Age"].fillna(method="bfill",inplace=True)
data["Embarked"].fillna(method="bfill",inplace=True)
data["Cabin"].fillna(method="bfill",inplace=True)
data["Cabin"].fillna(method="ffill",inplace=True)

#data["Cabin"].dropna(axis=0,inplace=True)

In [14]:
#LABEL ENCODER
from sklearn.preprocessing import LabelEncoder

le=["Cabin","Sex","Embarked"]

data[le]=data[le].apply(LabelEncoder().fit_transform)

In [15]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0         0       3    1  22.0      1      0   7.2500     81         2
1         1       1    0  38.0      1      0  71.2833     81         0
2         1       3    0  26.0      0      0   7.9250     55         2
3         1       1    0  35.0      1      0  53.1000     55         2
4         0       3    1  35.0      0      0   8.0500    129         2

In [16]:
x=data.iloc[:,1:]
y=data.iloc[:,:1]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2)

In [18]:
from sklearn import svm

In [20]:
clf=svm.SVC(gamma=0.01,C=100)

In [21]:
clf.fit(x_train,y_train)

E:\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(C=100, gamma=0.01)

In [22]:
y_pred=clf.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [36]:
(y_pred)

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0], dtype=int64)

In [26]:
confusion_matrix(y_test,y_pred)

array([[109,  51],
       [ 58,  50]], dtype=int64)

In [27]:
accuracy_score(y_test,y_pred)

0.5932835820895522

In [28]:
#SVM CAN ALSO BE USED FOR MULTICLASSIFICATION TECHNIQUE

# KNN

In [29]:
from sklearn import neighbors

In [30]:
knn = neighbors.KNeighborsClassifier(n_neighbors=3)

In [31]:
knn.fit(x_train,y_train)

<ipython-input-31-17b0ab828d68>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=3)

In [33]:
y_predk = knn.predict(x_test)

In [34]:
accuracy_score(y_test,y_predk)

0.5932835820895522

In [35]:
y_predk

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0], dtype=int64)

In [37]:
confusion_matrix(y_test,y_predk)

array([[111,  49],
       [ 60,  48]], dtype=int64)

# code

In [38]:
from sklearn.svm import SVC
SVC(gamma=0.01,C=100)

from sklearn.neighbors import KNeighborsClassifier
KNeighborsClassifier(n_neighbors=3)

KNeighborsClassifier(n_neighbors=3)

## SVM 

In [2]:
from sklearn.naive_bayes import BernoulliNB
#BernoulliNB.fit()

# CLASSIFICATION TECHNIQUES:-
## 1. NAIVE BAYES THEOREM:-
### Categorical,categorical,classifiaction technique used to classify records using probability.
## 2. K- NEAREST NEIGHBOUR(KNN):-
### Categorical,categorical and Continous,classifiaction technique used to classify records with the help of euclidean distance.
## 3. SUPPORT VECTOR MACHINE(SVM):-
### Categorical,categorical and classification,classifiaction technique used to classify records with the help of hyperplane and is capable of over-dimensional data.
