In [121]:
import numpy as np

In [122]:
import pandas as pd 

In [123]:
import matplotlib.pyplot as pyp 

In [124]:
from sklearn import preprocessing

In [132]:
data2=pd.read_csv("E:/AI ML/letsupgrade/Material/Day 25/train.csv")

In [133]:
data2.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [134]:
data2.count()

PassengerId    889
Survived       889
Pclass         889
Name           889
Sex            889
Age            889
SibSp          889
Parch          889
Ticket         889
Fare           889
Cabin          202
Embarked       889
dtype: int64

In [135]:
data2=data2.drop(["Name","Ticket","Cabin","Fare","PassengerId","Age"],axis=1)

In [136]:
data2

Survived  Pclass     Sex  SibSp  Parch Embarked
0           0       3    male      1      0        S
1           1       1  female      1      0        C
2           1       3  female      0      0        S
3           1       1  female      1      0        S
4           0       3    male      0      0        S
..        ...     ...     ...    ...    ...      ...
884         0       2    male      0      0        S
885         1       1  female      0      0        S
886         0       3  female      1      2        S
887         1       1    male      0      0        C
888         0       3    male      0      0        Q

[889 rows x 6 columns]

In [137]:
data2.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], dtype='object')

In [138]:
data2.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [139]:
from sklearn.preprocessing import LabelEncoder


In [140]:
encoder=LabelEncoder()

In [141]:
data2["Sex"]=encoder.fit_transform(data2.Sex)

In [142]:
data2["Embarked"]=encoder.fit_transform(data2.Embarked)

In [143]:
data2.head()

Survived  Pclass  Sex  SibSp  Parch  Embarked
0         0       3    1      1      0         2
1         1       1    0      1      0         0
2         1       3    0      0      0         2
3         1       1    0      1      0         2
4         0       3    1      0      0         2

In [56]:
from sklearn.naive_bayes import *

In [57]:
clf=BernoulliNB()

In [59]:
from sklearn.metrics import accuracy_score

In [60]:
from sklearn.metrics import confusion_matrix

# NAVE BAIYES applied to all categorical features with the help of function and looping:

In [144]:
li=[]
li=list(data2.columns)
li[0]
data2.head()

Survived  Pclass  Sex  SibSp  Parch  Embarked
0         0       3    1      1      0         2
1         1       1    0      1      0         0
2         1       3    0      0      0         2
3         1       1    0      1      0         2
4         0       3    1      0      0         2

In [149]:
def naivebayes():
    y=data2.iloc[:,i:i+1]
    y.head()
    x=data2.drop(li[i],axis=1)
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
    y_pred=clf.fit(x_train,y_train).predict(x_test)
    print("Accuracy score and Confusion matrix when "+li[i]+" is dependent variable and all others are independent variables\n")
    print(accuracy_score(y_test,y_pred,normalize=True))
    print("\n")
    print(confusion_matrix(y_test,y_pred))
    print("\n\n")

In [150]:
for i in range(len(li)):
    naivebayes()

Accuracy score and Confusion matrix when Survived is dependent variable and all others are independent variables

0.7715355805243446


[[131  26]
 [ 35  75]]



Accuracy score and Confusion matrix when Pclass is dependent variable and all others are independent variables

0.5880149812734082


[[ 26  10  34]
 [  8  10  31]
 [ 20   7 121]]



Accuracy score and Confusion matrix when Sex is dependent variable and all others are independent variables

0.7453183520599251


[[ 49  49]
 [ 19 150]]



Accuracy score and Confusion matrix when SibSp is dependent variable and all others are independent variables

0.6891385767790262


[[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]



Accuracy score and Confusion matrix when Parch is dependent variable and all others are independent variables

0.7153558052434457


[[182  16   0   

D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,